### PR TITLE
RPM specfile cleanup

### PR DESCRIPTION
**Pull request by xavierba**
This fixes issues #110 (03baf794dac5430c4f6e876840140ef7b8c20627) and #112 (182760b400f2deb2a9333f45f4ec5d76ee2f7a4b ; d5d0c199ce342e01d59fba5f9aac998204a468a3 ; c62a485eecb5f45f25843e8c8840ab62f094194d). It also tweaks quite a number of things here and there.

### CODE REVIEW

**Comment by kwizart** [comment]
Seems like very good work! thanks @xavierba 
I've tried to split issue but some can be closed at once with such PR.

Also I wonder why this non-standard:
`Requires:       %{real_name}-ltb%{?_isa} >= %{real_version}`
Isn't that
`Requires:       %{real_name}-ltb%{?_isa} = %{real_version}-%{release}`

**Comment by xavierba** [comment]
> Also I wonder why this non-standard: `Requires: %{real_name}-ltb%{?_isa} >= %{real_version}` Isn't that `Requires: %{real_name}-ltb%{?_isa} = %{real_version}-%{release}`

No idea, it was like that already, and I actually have the same question.

**Comment by coudot** [comment]
> > Also I wonder why this non-standard: `Requires: %{real_name}-ltb%{?_isa} >= %{real_version}` Isn't that `Requires: %{real_name}-ltb%{?_isa} = %{real_version}-%{release}`
> 
> No idea, it was like that already, and I actually have the same question.

I think it could be because we would like not force to update the base package but it seems not a real use case so I agree if you want to make it more standard

**Comment by coudot** [comment]
Thanks!

**Pull request merged**
